// styles/BMIGraphStyles.js
import { StyleSheet } from 'react-native';

export const bmiGraphStyles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  currentBMICard: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
  },
  currentBMIHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  currentBMILabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  currentBMIValue: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  currentBMIValueText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  currentBMICategory: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  currentBMIDate: {
    fontSize: 12,
    color: '#7f8c8d',
  },
  periodSelector: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  periodButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  periodButtonActive: {
    backgroundColor: '#3498db',
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  periodButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7f8c8d',
  },
  periodButtonTextActive: {
    color: '#ffffff',
  },
  graphWrapper: {
    marginBottom: 20,
  },
  graphContainer: {
    height: 240,
    position: 'relative',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 10,
  },
  referenceLines: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 20,
    bottom: 40,
  },
  referenceLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#e9ecef',
    flexDirection: 'row',
    alignItems: 'center',
  },
  referenceLineText: {
    fontSize: 10,
    color: '#95a5a6',
    backgroundColor: '#fafbfc',
    paddingHorizontal: 4,
    position: 'absolute',
    left: -15,
  },
  dataContainer: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 20,
    bottom: 40,
  },
  dataPoint: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  dataPointText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  connectionLine: {
    position: 'absolute',
    height: 2,
    backgroundColor: '#3498db',
    opacity: 0.6,
  },
  xAxisLabel: {
    position: 'absolute',
    fontSize: 10,
    color: '#7f8c8d',
    textAlign: 'center',
    width: 40,
  },
  noDataContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
    padding: 20,
  },
  noDataText: {
    fontSize: 48,
    marginBottom: 12,
  },
  noDataTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 8,
  },
  noDataSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 20,
  },
  loadingContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
  },
  loadingText: {
    fontSize: 16,
    color: '#7f8c8d',
  },
  legend: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 12,
    textAlign: 'center',
  },
  legendItems: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    width: '48%',
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendText: {
    fontSize: 12,
    color: '#2c3e50',
    flex: 1,
  },
});