// styles/WeightGraphStyles.js
import { StyleSheet } from 'react-native';

export const weightGraphStyles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  currentWeightCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#3498db',
  },
  currentWeightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  currentWeightLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  currentWeightValue: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#3498db',
  },
  currentWeightValueText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  trendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  trendLabel: {
    fontSize: 14,
    color: '#2c3e50',
    fontWeight: '600',
  },
  trendText: {
    fontSize: 14,
    fontWeight: '600',
  },
  currentWeightDate: {
    fontSize: 12,
    color: '#7f8c8d',
  },
  periodSelector: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  periodButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  periodButtonActive: {
    backgroundColor: '#3498db',
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  periodButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7f8c8d',
  },
  periodButtonTextActive: {
    color: '#ffffff',
  },
  graphWrapper: {
    marginBottom: 20,
  },
  graphContainer: {
    minHeight: 340,
    position: 'relative',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 10,
  },
  referenceLines: {
    position: 'absolute',
    left: 20,
    right: 60,
    top: 20,
    bottom: 60,
  },
  referenceLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#e9ecef',
    flexDirection: 'row',
    alignItems: 'center',
  },
  referenceLineText: {
    fontSize: 11,
    color: '#95a5a6',
    backgroundColor: '#fafbfc',
    paddingHorizontal: 6,
    paddingVertical: 2,
    position: 'absolute',
    left: -30,
    fontWeight: '500',
  },
  dataContainer: {
    position: 'absolute',
    left: 20,
    right: 60,
    top: 20,
    bottom: 60,
  },
  dataPoint: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  dataPointText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  connectionLine: {
    position: 'absolute',
    height: 3,
    backgroundColor: '#3498db',
    opacity: 0.7,
  },
  xAxisLabel: {
    position: 'absolute',
    fontSize: 11,
    color: '#7f8c8d',
    textAlign: 'center',
    width: 60,
    fontWeight: '500',
  },
  noDataContainer: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
    padding: 20,
  },
  noDataText: {
    fontSize: 48,
    marginBottom: 12,
  },
  noDataTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 8,
  },
  noDataSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 20,
  },
  loadingContainer: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafbfc',
    borderRadius: 12,
  },
  loadingText: {
    fontSize: 16,
    color: '#7f8c8d',
  },
  legend: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 12,
    textAlign: 'center',
  },
  legendItems: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    fontSize: 12,
    color: '#2c3e50',
    textAlign: 'center',
  },
});